name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: dropdown
    id: menu-type
    attributes:
      label: Which menu type were you using?
      multiple: false
      options:
        - Dine-in Non-AC Menu
        - Dine-in A/C Menu  
        - Take Away Menu
        - Admin Panel
        - All menu types
    validations:
      required: true

  - type: dropdown
    id: device-type
    attributes:
      label: What device were you using?
      multiple: false
      options:
        - Mobile Phone (Android)
        - Mobile Phone (iPhone)
        - Tablet (Android)
        - Tablet (iPad)
        - Desktop/Laptop (Windows)
        - Desktop/Laptop (Mac)
        - Desktop/Laptop (Linux)
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Samsung Internet
        - Other

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe what you expected to happen
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem
      placeholder: Drag and drop images/videos here or paste links
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true